apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: wedoo
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: wedoo-app
  template:
    metadata:
      labels:
        app: wedoo-app
    spec:
      containers:
      - name: wedoo-app
        image: {{ .Values.wedoo.image }}
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
       
