apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: wedoo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: wedoo-app
  template:
    metadata:
      labels:
        app: wedoo-app
    spec:
      containers:
      - name: wedoo-app
        image: registry.gitlab.com/blablabla123-cell/we_do_osm_flutter/test:8ad1372471eef8d7da10fc3fdbbd933260927cb2
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: gitlab-credentials
       
